spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Nikhil43@
    url: jdbc:mysql://localhost:3306/IHIS
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090